AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ociphp2

  Lumbda for generation thumbnail
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
Parameters:
  BucketName:
    Type: String
    Default: profile-img-abc-123-smoqadam
Resources:
  thumbnailMakerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command:
          - index # handler function
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub "${BucketName}"
        - S3FullAccessPolicy:
            BucketName: !Sub "${BucketName}-thumbnail"    
      Events:
        BucketEvent:
          Type: S3
          Properties:
            Bucket: !Ref ImageBucket
            Events:
              - 's3:ObjectCreated:*'
    Metadata:
      DockerTag: phpoci
      DockerContext: ./
      Dockerfile: Dockerfile
  
  ImageBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: !Sub "${BucketName}"
  
  ThumbBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: !Sub "${BucketName}-thumbnail"